stages:
  - build

build_apk:
  stage: build
  image: ghcr.io/cirruslabs/flutter:3.32.0  # Docker image Flutter
  
  before_script:
    - export VERSION=$(grep "^version:" pubspec.yaml | sed 's/version: //' | cut -d'+' -f1)
    - echo "version $VERSION+$CI_PIPELINE_IID"
    - sed -i "s/^version: .*/version: ${VERSION}+${CI_PIPELINE_IID}/" pubspec.yaml
    - grep "^version:" pubspec.yaml

  script:
    - flutter pub get
    - flutter build apk --release

  artifacts:
    name: "moody-study-v${CI_PIPELINE_IID}"
    paths:
      - build/app/outputs/flutter-apk/app-release.apk
    expire_in: 30 days  # APK disimpan 30 hari

  only:
    - main  # trigger tiap push ke branch main