name: moody_study
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+2=1

environment:
  sdk: '^3.11.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  audioplayers: ^6.0.0
  http: ^1.6.0
  file_picker: ^8.0.0
  image_cropper: ^7.0.0
  archive: ^3.3.0
  pdf: ^3.11.0
  path_provider: ^2.0.0
  open_file: ^3.2.1
  flutter_local_notifications: ^18.0.0
  timezone: ^0.9.0
  vibration: ^3.1.8
  spotify_sdk: ^3.0.2
  flutter_volume_controller: ^1.0.0
  http_parser: ^4.0.2
  provider: ^6.1.2
  dartz: ^0.10.1
  dio: ^5.4.0

  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1
  shared_preferences: ^2.5.5
  connectivity_plus: ^7.1.1
  easy_localization: ^3.0.7

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/audio/
    - assets/audio/alarm.mp3
    - assets/images/avatars/
    - assets/translations/
    - assets/images/hair/
    - assets/images/clothes/

  fonts:
    - family: BlackHanSans
      fonts:
        - asset: assets/fonts/BlackHanSans-Regular.ttf
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Regular.ttf
          weight: 400
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 700