name: moody_study
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '^3.11.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  audioplayers: ^6.0.0
  http: ^1.6.0
  file_picker: ^11.0.2
  archive: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/audio/

  fonts:
    - family: BlackHanSans
      fonts:
        - asset: assets/fonts/BlackHanSans-Regular.ttf
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Regular.ttf
          weight: 400
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 700